# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'barbot' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for barbot
  target 'barbot' do
	pod 'Gloss', '2.0.0-beta.1'
    pod 'Starscream', '~> 3.0.2'
  end
end
